chat_words_str = """
afaik=as far as i know
afk=away from keyboard
asap=as soon as possible
atk=at the keyboard
atm=at the moment
a3=anytime anywhere anyplace
bak=back at keyboard
bbl=be back later
bbs=be back soon
bfn=bye for now
b4n=bye for now
brb=be right back
brt=be right there
btw=by the way
k = okay
b4=before
pr=pull request
rfc=request for comments
wip=work in progress
utack=agree with the changes and reviewed them, but didn’t test
ack=agree with the idea
cu=see you
cul8r=see you later
cya=see you
faq=frequently asked questions
fc=fingers crossed
fwiw=for what it is worth
fyi=for your information
gal=get a life
gg=good game
gn=good night
gmta=great minds think alike
gr8=great
g9=genius
ic=i see
icq=i seek you
ilu=i love you
imho=in my honest humble opinion
imo=in my opinion
iow=in other words
irl=in real life
ldr=long distance relationship
lmao=laugh my ass off
lol=laughing out loud
ltns=long time no see
l8r=later
mte=my thoughts exactly
m8=mate
nrn=no reply necessary
oic=oh i see
pita=pain in the ass
prt=party
prw=parents are watching
qpsa=que pasa
rofl=rolling on the floor laughing
roflol=rolling on the floor laughing out loud
rotflmao=rolling on the floor laughing my ass off
sk8=skate
stats=your sex and age
asl=age sex location
thx=thank you
ttfn=ta ta for now
ttyl=talk to you later
u2=you too
u4e=yours for ever
wb=welcome back
wtf=what the fuck
wtg=way to go
wuf=where are you from
w8=wait
7k=sick laugher
tfw=that feeling when
mfw=my face when
mrw=my reaction when
ifyp=i feel your pain
tntl=trying not to laugh
jk=just kidding
ily=i love you
imu=i miss you
adih=another day in hell
idc=i dont care
wywh=wish you were here
bae=before anyone else
fimh=forever in my heart
bsaaw=big smile and a wink
bwl=bursting with laughter
bff=best friends forever
csl=cant stop laughing
lgtm=looks good to me
2f4u=too fast for you
4yeo=for your eyes only
fyeo=for your eyes only
aamof=as a matter of fact
afair=as far as i remember
aka=also known as
btt=back to topic
b/c=because
c&p=copy and paste
diy=do it yourself
eobd=end of business day
eod=end of discussion
eom=end of message
eot=end of thread text transmission
fack=full acknowledge
fka=formerly known as
jfyi=just for your information
ftw=for the win
hf=have fun
hth=hope this helps
idk=i dont know
iirc=if i remember correctly
imnsho=in my not so honest opinion
itt=in this thread
dgmw=don't get me wrong
mmw=mark my words
n/a=not available
nan=not a number
nntr=no need to reply
noob=newbie
noyb=none of your business
omg=oh my god
op=original post
ot=off topic
otoh=on the other hand
pebkac=problem exists between keyboard and chair
pov=point of view
rotfl=rolling on the floor laughing
rtfm=read the fine manual
scnr=sorry could not resist
sflr=sorry for late reply
spoc=single point of contact
tba=to be announced
tbc=to be continued
tia=thanks in advance
tgif=thanks god its friday
tq=thank you
tyvm=thank you very much
tyt=take your time
wfm=works for me
wrt=with regard to
wth=what the hell
ymmd=you made my day
ymmv=your mileage may vary
yam=yet another meeting
icymi=in case you missed it
2moro=tomorrow
2nte=tonight
aeap=as early as possible
alap=as late as possible
b4yki=before you know it
bmbae=be my bae
bm&y=between me and you
btam=be that as it may
ctn=cannot talk now
cus=see you soon
cwot=complete waste of time
cyt=see you tomorrow
f2f=face to face
foaf=friend of a friend
hak=hugs and kisses
jc=just checking
jtlyk=just to let you know
kfy=kiss for you
kmn=kill me now
kpc=keeping parents clueless
mtfbwy=may the force be with you
myob=mind your own business
nc=no comment
nimby=not in my backyard
nm=never mind
np=no problem
nsfw=not safe for work
ntim=not that it matters
nvm=never mind
oatus=on a totally unrelated subject
omw=on my way
otl=out to lunch
otp=on the phone
p911=parent alert
pal=parents are listening
paw=parents are watching
pir=parent in room
pos=parent over shoulder
qt=cutie
rn=right now
ru=are you
sep=someone elses problem
sitd=still in the dark
slap=sounds like a plan
smim=send me an instant message
tmi=too much information
wycm=will you call me
"""