chat_words_str = """
afaik=as far as i know
afk=away from keyboard
atk=at the keyboard
atm=at the moment
a3=anytime anywhere anyplace
bak=back at keyboard
bbl=be back later
bbs=be back soon
bfn=bye for now
b4n=bye for now
brb=be right back
brt=be right there
btw=by the way
k=okay
b4=before
pr=pull request
rfc=request for comments
wip=work in progress
utack=agree with the changes and reviewed them, but didn’t test
ack=agree with the idea
cu=see you
cul8r=see you later
cya=see you
faq=frequently asked questions
fc=fingers crossed
fwiw=for what it is worth
fyi=for your information
gal=get a life
gg=good game
gn=good night
gmta=great minds think alike
gr8=great
g9=genius
ic=i see
icq=i seek you
ilu=i love you
imho=in my honest humble opinion
imo=in my opinion
iow=in other words
irl=in real life
ldr=long distance relationship
lmao=laugh my ass off
lol=laughing out loud
ltns=long time no see
l8r=later
mte=my thoughts exactly
m8=mate
nrn=no reply necessary
oic=oh i see
pita=pain in the ass
prt=party
prw=parents are watching
qpsa=que pasa
rofl=rolling on the floor laughing
roflol=rolling on the floor laughing out loud
rotflmao=rolling on the floor laughing my ass off
sk8=skate
stats=your sex and age
asl=age sex location
thx=thank you
ttfn=ta ta for now
ttyl=talk to you later
u2=you too
u4e=yours for ever
wb=welcome back
wtf=what the fuck
wtg=way to go
wuf=where are you from
w8=wait
7k=sick laugher
tfw=that feeling when
mfw=my face when
mrw=my reaction when
ifyp=i feel your pain
tntl=trying not to laugh
jk=just kidding
ily=i love you
imu=i miss you
adih=another day in hell
idc=i dont care
wywh=wish you were here
bae=before anyone else
fimh=forever in my heart
bsaaw=big smile and a wink
bwl=bursting with laughter
bff=best friends forever
csl=cant stop laughing
lgtm=looks good to me
2f4u=too fast for you
4yeo=for your eyes only
fyeo=for your eyes only
aamof=as a matter of fact
afair=as far as i remember
aka=also known as
btt=back to topic
b/c=because
c&p=copy and paste
diy=do it yourself
eom=end of message
eot=end of thread text transmission
fack=full acknowledge
fka=formerly known as
jfyi=just for your information
ftw=for the win
hf=have fun
hth=hope this helps
idk=i dont know
iirc=if i remember correctly
imnsho=in my not so honest opinion
itt=in this thread
dgmw=don't get me wrong
mmw=mark my words
n/a=not available
nan=not a number
nntr=no need to reply
noob=newbie
noyb=none of your business
omg=oh my god
op=original post
ot=off topic
otoh=on the other hand
pebkac=problem exists between keyboard and chair
pov=point of view
rotfl=rolling on the floor laughing
rtfm=read the fine manual
scnr=sorry could not resist
sflr=sorry for late reply
spoc=single point of contact
tba=to be announced
tbc=to be continued
tia=thanks in advance
tgif=thanks god its friday
tq=thank you
tyvm=thank you very much
tyt=take your time
wfm=works for me
wrt=with regard to
wth=what the hell
ymmd=you made my day
ymmv=your mileage may vary
yam=yet another meeting
icymi=in case you missed it
2moro=tomorrow
2nte=tonight
aeap=as early as possible
alap=as late as possible
b4yki=before you know it
bmbae=be my bae
bm&y=between me and you
btam=be that as it may
ctn=cannot talk now
cus=see you soon
cwot=complete waste of time
cyt=see you tomorrow
f2f=face to face
foaf=friend of a friend
hak=hugs and kisses
jc=just checking
jtlyk=just to let you know
kfy=kiss for you
kmn=kill me now
kpc=keeping parents clueless
mtfbwy=may the force be with you
myob=mind your own business
nc=no comment
nimby=not in my backyard
nm=never mind
np=no problem
nsfw=not safe for work
ntim=not that it matters
nvm=never mind
oatus=on a totally unrelated subject
omw=on my way
otl=out to lunch
otp=on the phone
p911=parent alert
pal=parents are listening
paw=parents are watching
pir=parent in room
pos=parent over shoulder
qt=cutie
rn=right now
ru=are you
sep=someone elses problem
sitd=still in the dark
slap=sounds like a plan
smim=send me an instant message
tmi=too much information
wycm=will you call me
AFAIK=AS FAR AS I KNOW
AFK=AWAY FROM KEYBOARD
ATK=AT THE KEYBOARD
ATM=AT THE MOMENT
A3=ANYTIME ANYWHERE ANYPLACE
BAK=BACK AT KEYBOARD
BBL=BE BACK LATER
BBS=BE BACK SOON
BFN=BYE FOR NOW
B4N=BYE FOR NOW
BRB=BE RIGHT BACK
BRT=BE RIGHT THERE
BTW=BY THE WAY
K=OKAY
B4=BEFORE
PR=PULL REQUEST
PR=PULL REQUEST
RFC=REQUEST FOR COMMENTS
WIP=WORK IN PROGRESS
UTACK=AGREE WITH THE CHANGES AND REVIEWED THEM, BUT DIDN’T TEST
ACK=AGREE WITH THE IDEA
CU=SEE YOU
CUL8R=SEE YOU LATER
CYA=SEE YOU
FAQ=FREQUENTLY ASKED QUESTIONS
FC=FINGERS CROSSED
FWIW=FOR WHAT IT IS WORTH
FYI=FOR YOUR INFORMATION
GAL=GET A LIFE
GG=GOOD GAME
GN=GOOD NIGHT
GMTA=GREAT MINDS THINK ALIKE
GR8=GREAT
G9=GENIUS
IC=I SEE
ICQ=I SEEK YOU
ILU=I LOVE YOU
IMHO=IN MY HONEST HUMBLE OPINION
IMO=IN MY OPINION
IOW=IN OTHER WORDS
IRL=IN REAL LIFE
LDR=LONG DISTANCE RELATIONSHIP
LMAO=LAUGH MY ASS OFF
LOL=LAUGHING OUT LOUD
LTNS=LONG TIME NO SEE
L8R=LATER
MTE=MY THOUGHTS EXACTLY
M8=MATE
NRN=NO REPLY NECESSARY
OIC=OH I SEE
PITA=PAIN IN THE ASS
PRT=PARTY
PRW=PARENTS ARE WATCHING
QPSA=QUE PASA
ROFL=ROLLING ON THE FLOOR LAUGHING
ROFLOL=ROLLING ON THE FLOOR LAUGHING OUT LOUD
ROTFLMAO=ROLLING ON THE FLOOR LAUGHING MY ASS OFF
SK8=SKATE
STATS=YOUR SEX AND AGE
ASL=AGE SEX LOCATION
THX=THANK YOU
TTFN=TA TA FOR NOW
TTYL=TALK TO YOU LATER
U2=YOU TOO
U4E=YOURS FOR EVER
WB=WELCOME BACK
WTF=WHAT THE FUCK
WTG=WAY TO GO
WUF=WHERE ARE YOU FROM
W8=WAIT
7K=SICK LAUGHER
TFW=THAT FEELING WHEN
MFW=MY FACE WHEN
MRW=MY REACTION WHEN
IFYP=I FEEL YOUR PAIN
TNTL=TRYING NOT TO LAUGH
JK=JUST KIDDING
ILY=I LOVE YOU
IMU=I MISS YOU
ADIH=ANOTHER DAY IN HELL
IDC=I DONT CARE
WYWH=WISH YOU WERE HERE
BAE=BEFORE ANYONE ELSE
FIMH=FOREVER IN MY HEART
BSAAW=BIG SMILE AND A WINK
BWL=BURSTING WITH LAUGHTER
BFF=BEST FRIENDS FOREVER
CSL=CANT STOP LAUGHING
LGTM=LOOKS GOOD TO ME
2F4U=TOO FAST FOR YOU
4YEO=FOR YOUR EYES ONLY
FYEO=FOR YOUR EYES ONLY
AAMOF=AS A MATTER OF FACT
AFAIR=AS FAR AS I REMEMBER
AKA=ALSO KNOWN AS
BTT=BACK TO TOPIC
B/C=BECAUSE
C&P=COPY AND PASTE
DIY=DO IT YOURSELF
EOM=END OF MESSAGE
EOT=END OF THREAD TEXT TRANSMISSION
FACK=FULL ACKNOWLEDGE
FKA=FORMERLY KNOWN AS
JFYI=JUST FOR YOUR INFORMATION
FTW=FOR THE WIN
HF=HAVE FUN
HTH=HOPE THIS HELPS
IDK=I DONT KNOW
IIRC=IF I REMEMBER CORRECTLY
IMNSHO=IN MY NOT SO HONEST OPINION
ITT=IN THIS THREAD
DGMW=DON'T GET ME WRONG
MMW=MARK MY WORDS
N/A=NOT AVAILABLE
NAN=NOT A NUMBER
NNTR=NO NEED TO REPLY
NOOB=NEWBIE
NOYB=NONE OF YOUR BUSINESS
OMG=OH MY GOD
OP=ORIGINAL POST
OT=OFF TOPIC
OTOH=ON THE OTHER HAND
PEBKAC=PROBLEM EXISTS BETWEEN KEYBOARD AND CHAIR
POV=POINT OF VIEW
ROTFL=ROLLING ON THE FLOOR LAUGHING
RTFM=READ THE FINE MANUAL
SCNR=SORRY COULD NOT RESIST
SFLR=SORRY FOR LATE REPLY
SPOC=SINGLE POINT OF CONTACT
TBA=TO BE ANNOUNCED
TBC=TO BE CONTINUED
TIA=THANKS IN ADVANCE
TGIF=THANKS GOD ITS FRIDAY
TQ=THANK YOU
TYVM=THANK YOU VERY MUCH
TYT=TAKE YOUR TIME
WFM=WORKS FOR ME
WRT=WITH REGARD TO
WTH=WHAT THE HELL
YMMD=YOU MADE MY DAY
YMMV=YOUR MILEAGE MAY VARY
YAM=YET ANOTHER MEETING
ICYMI=IN CASE YOU MISSED IT
2MORO=TOMORROW
2NTE=TONIGHT
AEAP=AS EARLY AS POSSIBLE
ALAP=AS LATE AS POSSIBLE
B4YKI=BEFORE YOU KNOW IT
BMBAE=BE MY BAE
BM&Y=BETWEEN ME AND YOU
BTAM=BE THAT AS IT MAY
CTN=CANNOT TALK NOW
CUS=SEE YOU SOON
CWOT=COMPLETE WASTE OF TIME
CYT=SEE YOU TOMORROW
F2F=FACE TO FACE
FOAF=FRIEND OF A FRIEND
HAK=HUGS AND KISSES
JC=JUST CHECKING
JTLYK=JUST TO LET YOU KNOW
KFY=KISS FOR YOU
KMN=KILL ME NOW
KPC=KEEPING PARENTS CLUELESS
MTFBWY=MAY THE FORCE BE WITH YOU
MYOB=MIND YOUR OWN BUSINESS
NC=NO COMMENT
NIMBY=NOT IN MY BACKYARD
NM=NEVER MIND
NP=NO PROBLEM
NSFW=NOT SAFE FOR WORK
NTIM=NOT THAT IT MATTERS
NVM=NEVER MIND
OATUS=ON A TOTALLY UNRELATED SUBJECT
OMW=ON MY WAY
OTL=OUT TO LUNCH
OTP=ON THE PHONE
P911=PARENT ALERT
PAL=PARENTS ARE LISTENING
PAW=PARENTS ARE WATCHING
PIR=PARENT IN ROOM
POS=PARENT OVER SHOULDER
QT=CUTIE
RN=RIGHT NOW
RU=ARE YOU
SEP=SOMEONE ELSES PROBLEM
SITD=STILL IN THE DARK
SLAP=SOUNDS LIKE A PLAN
SMIM=SEND ME AN INSTANT MESSAGE
TMI=TOO MUCH INFORMATION
WYCM=WILL YOU CALL ME
"""